<h1>POSTTEST 8</h1>
<a href='https://github.com/2009106055/Praktikum_KB'>Link Github</a>

<h5>Import Library/Package</h5>

In [184]:
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import train_test_split

<h5>Import Database Yang Kita Punya</h5>

In [185]:
dataset = pd.read_csv('FIFA22_PlayerCards.csv')
dataset

,PlayerName,Foot,Position,AWR,DWR,OVR,PAC,SHO,PAS,DRI,DEF,PHY,SM,DIV,POS,HAN,REF,KIC,SPD
0,Pelé,Right,CAM,High,Med,98,95.0,96.0,93.0,96.0,60.0,76.0,5,NaN,NaN,NaN,NaN,NaN,NaN
1,Diego Maradona,Left,CAM,High,Med,97,92.0,93.0,92.0,97.0,40.0,76.0,5,NaN,NaN,NaN,NaN,NaN,NaN
2,Ronaldo,Right,ST,Med,Med,96,97.0,95.0,81.0,95.0,45.0,76.0,5,NaN,NaN,NaN,NaN,NaN,NaN
3,Zinedine Zidane,Right,CAM,Med,Med,96,85.0,92.0,96.0,95.0,75.0,86.0,5,NaN,NaN,NaN,NaN,NaN,NaN
4,Diego Maradona,Left,CAM,High,Med,95,88.0,91.0,90.0,95.0,42.0,75.0,5,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15923,Patrick McGarvey,Right,GK,Med,Med,48,NaN,NaN,NaN,NaN,NaN,NaN,1,49.0,43.0,47.0,51.0,47.0,31.0
15924,Lalbiakhlua Jongte,Left,GK,Med,Med,48,NaN,NaN,NaN,NaN,NaN,NaN,1,49.0,48.0,46.0,47.0,48.0,18.0
15925,Muheet Shabir Khan,Right,GK,Med,Med,48,NaN,NaN,NaN,NaN,NaN,NaN,1,49.0,45.0,50.0,47.0,46.0,22.0
15926,Arsh Shaikh,Right,GK,Med,Med,47,NaN,NaN,NaN,NaN,NaN,NaN,1,49.0,45.0,41.0,49.0,39.0,19.0
15927,Revanth By,Right,GK,Med,Med,47,NaN,NaN,NaN,NaN,NaN,NaN,1,49.0,47.0,46.0,52.0,43.0,21.0

<h5>preprocessing data Di sini saya mencoba menggunakan Encoding untuk mengganti nilai-nilai bertipe data objek menjadi tipe data angka</h5>

In [186]:
varEncoder = OrdinalEncoder()
dataset['Foot'] = varEncoder.fit_transform(dataset[['Foot']])
dataset['AWR'] = varEncoder.fit_transform(dataset[['AWR']])
dataset['DWR'] = varEncoder.fit_transform(dataset[['DWR']])
dataset['Position'] = varEncoder.fit_transform(dataset[['Position']])

In [187]:
dataset

,PlayerName,Foot,Position,AWR,DWR,OVR,PAC,SHO,PAS,DRI,DEF,PHY,SM,DIV,POS,HAN,REF,KIC,SPD
0,Pelé,1.0,0.0,0.0,2.0,98,95.0,96.0,93.0,96.0,60.0,76.0,5,NaN,NaN,NaN,NaN,NaN,NaN
1,Diego Maradona,0.0,0.0,0.0,2.0,97,92.0,93.0,92.0,97.0,40.0,76.0,5,NaN,NaN,NaN,NaN,NaN,NaN
2,Ronaldo,1.0,16.0,2.0,2.0,96,97.0,95.0,81.0,95.0,45.0,76.0,5,NaN,NaN,NaN,NaN,NaN,NaN
3,Zinedine Zidane,1.0,0.0,2.0,2.0,96,85.0,92.0,96.0,95.0,75.0,86.0,5,NaN,NaN,NaN,NaN,NaN,NaN
4,Diego Maradona,0.0,0.0,0.0,2.0,95,88.0,91.0,90.0,95.0,42.0,75.0,5,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15923,Patrick McGarvey,1.0,5.0,2.0,2.0,48,NaN,NaN,NaN,NaN,NaN,NaN,1,49.0,43.0,47.0,51.0,47.0,31.0
15924,Lalbiakhlua Jongte,0.0,5.0,2.0,2.0,48,NaN,NaN,NaN,NaN,NaN,NaN,1,49.0,48.0,46.0,47.0,48.0,18.0
15925,Muheet Shabir Khan,1.0,5.0,2.0,2.0,48,NaN,NaN,NaN,NaN,NaN,NaN,1,49.0,45.0,50.0,47.0,46.0,22.0
15926,Arsh Shaikh,1.0,5.0,2.0,2.0,47,NaN,NaN,NaN,NaN,NaN,NaN,1,49.0,45.0,41.0,49.0,39.0,19.0
15927,Revanth By,1.0,5.0,2.0,2.0,47,NaN,NaN,NaN,NaN,NaN,NaN,1,49.0,47.0,46.0,52.0,43.0,21.0

<h5>Menentukan record dan label</h5>

In [188]:
x = dataset[['Foot','Position','AWR','DWR','OVR']]
y = dataset[['SM']]

<h5>Membagi data train pada variabel independen menjadi data train dan data test. Di sini saya menggunakan proporsi 70:30 (70% Data train dan 30% Data test)</h5>

In [189]:

x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=0, test_size=.3)

<h5>menampilkan hasil x_train,x_test,y_train,y_test</h5>

In [190]:
print(f'panjang x train : {len(x_train)}',
f'panjang y train : {len(y_train)}',
f'panjang x test : {len(x_test)}',
f'panjang y test : {len(y_test)}')

panjang x train : 14335 panjang y train : 14335 panjang x test : 1593 panjang y test : 1593

<h5>Di sini saya menetapkan jumlah kelas sebesar 2 (sesuaikan dengan jumlah kelas yang dimiliki dataset)<h5>

In [191]:
num_class = 6
y_train = tf.keras.utils.to_categorical(y_train, num_class)
y_test = tf.keras.utils.to_categorical(y_test, num_class)

<h5>Buat model sequential dengan total layer sebanyak 5 layer menggunakan aktivasi relu pada 4 layer pertama dan aktivasi sigmoid pada layer terakhir, lalu tampilkan model tersebut dengan fungsi summary()</h5>

In [192]:
seq = tf.keras.Sequential([
    tf.keras.layers.Dense(16, activation='relu', input_dim=5),
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.Dense(16, activation='relu'),
    tf.keras.layers.Dense(num_class, activation='sigmoid')
])
seq.summary()

Model: "sequential_20"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_85 (Dense)            (None, 16)                96

 dense_86 (Dense)            (None, 32)                544

 dense_87 (Dense)            (None, 32)                1056

 dense_88 (Dense)            (None, 16)                528

 dense_89 (Dense)            (None, 6)                 102

=================================================================
Total params: 2,326
Trainable params: 2,326
Non-trainable params: 0
_________________________________________________________________

<h5>Lakukan Proses Compile</h5>

In [193]:
seq.compile(
    optimizer=tf.keras.optimizers.Adam(),
    loss=tf.keras.losses.categorical_crossentropy,
    metrics=['accuracy']
)

<h5>Lakukan proses model training dengan fit</h5>

In [195]:
accuracy = seq.fit(
    x = x_train,  y = y_train,
    validation_data = (x_test, y_test),
    epochs = 50,
    steps_per_epoch = 250,
    verbose = 2 ## tampilan compile per epoch 1 default, 2 tidak melihatkan perjalanan 0 langsung 
)

Epoch 1/50
250/250 - 1s - loss: nan - accuracy: 4.1520e-04 - val_loss: nan - val_accuracy: 6.2775e-04 - 790ms/epoch - 3ms/step
Epoch 2/50
250/250 - 1s - loss: nan - accuracy: 4.1520e-04 - val_loss: nan - val_accuracy: 6.2775e-04 - 520ms/epoch - 2ms/step
Epoch 3/50
250/250 - 0s - loss: nan - accuracy: 4.1520e-04 - val_loss: nan - val_accuracy: 6.2775e-04 - 491ms/epoch - 2ms/step
Epoch 4/50
250/250 - 0s - loss: nan - accuracy: 4.1520e-04 - val_loss: nan - val_accuracy: 6.2775e-04 - 499ms/epoch - 2ms/step
Epoch 5/50
250/250 - 0s - loss: nan - accuracy: 4.1520e-04 - val_loss: nan - val_accuracy: 6.2775e-04 - 495ms/epoch - 2ms/step
Epoch 6/50
250/250 - 0s - loss: nan - accuracy: 4.1520e-04 - val_loss: nan - val_accuracy: 6.2775e-04 - 498ms/epoch - 2ms/step
Epoch 7/50
250/250 - 1s - loss: nan - accuracy: 4.1520e-04 - val_loss: nan - val_accuracy: 6.2775e-04 - 508ms/epoch - 2ms/step
Epoch 8/50
250/250 - 1s - loss: nan - accuracy: 4.1520e-04 - val_loss: nan - val_accuracy: 6.2775e-04 - 516ms/epoch - 2ms/step
Epoch 9/50
250/250 - 0s - loss: nan - accuracy: 5.5359e-04 - val_loss: nan - val_accuracy: 6.2775e-04 - 497ms/epoch - 2ms/step
Epoch 10/50
250/250 - 1s - loss: nan - accuracy: 3.4600e-04 - val_loss: nan - val_accuracy: 6.2775e-04 - 522ms/epoch - 2ms/step
Epoch 11/50
250/250 - 0s - loss: nan - accuracy: 3.4600e-04 - val_loss: nan - val_accuracy: 6.2775e-04 - 499ms/epoch - 2ms/step
Epoch 12/50
250/250 - 1s - loss: nan - accuracy: 4.1520e-04 - val_loss: nan - val_accuracy: 6.2775e-04 - 502ms/epoch - 2ms/step
Epoch 13/50
250/250 - 1s - loss: nan - accuracy: 4.8440e-04 - val_loss: nan - val_accuracy: 6.2775e-04 - 583ms/epoch - 2ms/step
Epoch 14/50
250/250 - 1s - loss: nan - accuracy: 3.4600e-04 - val_loss: nan - val_accuracy: 6.2775e-04 - 521ms/epoch - 2ms/step
Epoch 15/50
250/250 - 0s - loss: nan - accuracy: 4.8440e-04 - val_loss: nan - val_accuracy: 6.2775e-04 - 498ms/epoch - 2ms/step
Epoch 16/50
250/250 - 1s - loss: nan - accuracy: 4.8440e-04 - val_loss: nan - val_accuracy: 6.2775e-04 - 704ms/epoch - 3ms/step
Epoch 17/50
250/250 - 1s - loss: nan - accuracy: 2.7680e-04 - val_loss: nan - val_accuracy: 6.2775e-04 - 734ms/epoch - 3ms/step
Epoch 18/50
250/250 - 1s - loss: nan - accuracy: 4.1520e-04 - val_loss: nan - val_accuracy: 6.2775e-04 - 735ms/epoch - 3ms/step
Epoch 19/50
250/250 - 1s - loss: nan - accuracy: 5.5359e-04 - val_loss: nan - val_accuracy: 6.2775e-04 - 761ms/epoch - 3ms/step
Epoch 20/50
250/250 - 1s - loss: nan - accuracy: 2.7680e-04 - val_loss: nan - val_accuracy: 6.2775e-04 - 581ms/epoch - 2ms/step
Epoch 21/50
250/250 - 1s - loss: nan - accuracy: 4.1520e-04 - val_loss: nan - val_accuracy: 6.2775e-04 - 521ms/epoch - 2ms/step
Epoch 22/50
250/250 - 1s - loss: nan - accuracy: 4.8440e-04 - val_loss: nan - val_accuracy: 6.2775e-04 - 501ms/epoch - 2ms/step
Epoch 23/50
250/250 - 0s - loss: nan - accuracy: 3.4600e-04 - val_loss: nan - val_accuracy: 6.2775e-04 - 491ms/epoch - 2ms/step
Epoch 24/50
250/250 - 1s - loss: nan - accuracy: 4.1520e-04 - val_loss: nan - val_accuracy: 6.2775e-04 - 510ms/epoch - 2ms/step
Epoch 25/50
250/250 - 0s - loss: nan - accuracy: 4.8440e-04 - val_loss: nan - val_accuracy: 6.2775e-04 - 492ms/epoch - 2ms/step
Epoch 26/50
250/250 - 1s - loss: nan - accuracy: 4.1520e-04 - val_loss: nan - val_accuracy: 6.2775e-04 - 506ms/epoch - 2ms/step
Epoch 27/50
250/250 - 1s - loss: nan - accuracy: 4.1520e-04 - val_loss: nan - val_accuracy: 6.2775e-04 - 502ms/epoch - 2ms/step
Epoch 28/50
250/250 - 0s - loss: nan - accuracy: 4.8440e-04 - val_loss: nan - val_accuracy: 6.2775e-04 - 496ms/epoch - 2ms/step
Epoch 29/50
250/250 - 0s - loss: nan - accuracy: 5.5359e-04 - val_loss: nan - val_accuracy: 6.2775e-04 - 492ms/epoch - 2ms/step
Epoch 30/50
250/250 - 1s - loss: nan - accuracy: 2.0760e-04 - val_loss: nan - val_accuracy: 6.2775e-04 - 505ms/epoch - 2ms/step
Epoch 31/50
250/250 - 0s - loss: nan - accuracy: 4.1520e-04 - val_loss: nan - val_accuracy: 6.2775e-04 - 496ms/epoch - 2ms/step
Epoch 32/50
250/250 - 0s - loss: nan - accuracy: 4.1520e-04 - val_loss: nan - val_accuracy: 6.2775e-04 - 493ms/epoch - 2ms/step
Epoch 33/50
250/250 - 0s - loss: nan - accuracy: 3.4600e-04 - val_loss: nan - val_accuracy: 6.2775e-04 - 489ms/epoch - 2ms/step
Epoch 34/50
250/250 - 0s - loss: nan - accuracy: 4.8440e-04 - val_loss: nan - val_accuracy: 6.2775e-04 - 494ms/epoch - 2ms/step
Epoch 35/50
250/250 - 0s - loss: nan - accuracy: 3.4600e-04 - val_loss: nan - val_accuracy: 6.2775e-04 - 491ms/epoch - 2ms/step
Epoch 36/50
250/250 - 1s - loss: nan - accuracy: 4.8440e-04 - val_loss: nan - val_accuracy: 6.2775e-04 - 504ms/epoch - 2ms/step
Epoch 37/50
250/250 - 0s - loss: nan - accuracy: 4.8440e-04 - val_loss: nan - val_accuracy: 6.2775e-04 - 498ms/epoch - 2ms/step
Epoch 38/50
250/250 - 0s - loss: nan - accuracy: 4.8440e-04 - val_loss: nan - val_accuracy: 6.2775e-04 - 492ms/epoch - 2ms/step
Epoch 39/50
250/250 - 0s - loss: nan - accuracy: 3.4600e-04 - val_loss: nan - val_accuracy: 6.2775e-04 - 488ms/epoch - 2ms/step
Epoch 40/50
250/250 - 0s - loss: nan - accuracy: 2.7680e-04 - val_loss: nan - val_accuracy: 6.2775e-04 - 488ms/epoch - 2ms/step
Epoch 41/50
250/250 - 0s - loss: nan - accuracy: 6.2279e-04 - val_loss: nan - val_accuracy: 6.2775e-04 - 492ms/epoch - 2ms/step
Epoch 42/50
250/250 - 1s - loss: nan - accuracy: 4.8440e-04 - val_loss: nan - val_accuracy: 6.2775e-04 - 500ms/epoch - 2ms/step
Epoch 43/50
250/250 - 0s - loss: nan - accuracy: 2.0760e-04 - val_loss: nan - val_accuracy: 6.2775e-04 - 488ms/epoch - 2ms/step
Epoch 44/50
250/250 - 1s - loss: nan - accuracy: 4.1520e-04 - val_loss: nan - val_accuracy: 6.2775e-04 - 507ms/epoch - 2ms/step
Epoch 45/50
250/250 - 0s - loss: nan - accuracy: 4.8440e-04 - val_loss: nan - val_accuracy: 6.2775e-04 - 490ms/epoch - 2ms/step
Epoch 46/50
250/250 - 1s - loss: nan - accuracy: 3.4600e-04 - val_loss: nan - val_accuracy: 6.2775e-04 - 649ms/epoch - 3ms/step
Epoch 47/50
250/250 - 1s - loss: nan - accuracy: 5.5359e-04 - val_loss: nan - val_accuracy: 6.2775e-04 - 608ms/epoch - 2ms/step
Epoch 48/50
250/250 - 1s - loss: nan - accuracy: 4.8440e-04 - val_loss: nan - val_accuracy: 6.2775e-04 - 602ms/epoch - 2ms/step
Epoch 49/50
250/250 - 1s - loss: nan - accuracy: 2.0760e-04 - val_loss: nan - val_accuracy: 6.2775e-04 - 508ms/epoch - 2ms/step
Epoch 50/50
WARNING:tensorflow:Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches (in this case, 12500 batches). You may need to use the repeat() function when building your dataset.
250/250 - 0s - loss: nan - accuracy: 5.7797e-04 - val_loss: nan - val_accuracy: 6.2775e-04 - 368ms/epoch - 1ms/step

<h5>Melakukan Model Save dan menyimpan nya ke dalam format hdf5</h5>

In [196]:
seq.save('model/seq_1.h5')